import type { Option } from './types';

// FIX: Add ZALO_COMMUNITY_LINK to fix import error in components/Footer.tsx
export const ZALO_COMMUNITY_LINK = 'https://zalo.me/g/your_group_id_here';

export const KID_PROMPT_OPTIONS: Option[] = [
  {
    id: 'prompt-1',
    label: 'Bé trai & Lân',
    value: `A high-resolution studio photograph of a young Vietnamese boy dressed in a traditional red 'áo gấm' with golden patterns. He is joyfully holding a vibrant, traditional star-shaped lantern in one hand. He is sitting on a dark wooden stool next to a large, ornate lion dance head. The background is festive, featuring hanging red lanterns of various shapes, a large, softly glowing full moon, and a table with mooncakes and a small teapot. The boy has a cheerful expression.
Important: Keep the boy’s face exactly as provided, natural and unedited, with face consistency.
Captured with the latest Canon EOS R5 and RF 85mm f/1.2L lens, ultra-high resolution, natural studio lighting with soft diffusion, gentle warm tones, realistic color grading, balanced highlights and shadows.`
  },
  {
    id: 'prompt-2',
    label: 'Bé gái & Áo dài',
    value: `A high-resolution studio photograph of a young Vietnamese girl wearing an elegant, pastel pink traditional 'áo dài' with delicate lotus flower embroidery. Her hair is styled in a neat braid adorned with a small, pearl hairpin. She is standing gracefully, holding a folded paper fan. The setting is a serene indoor courtyard with a circular moon gate in the background, through which a glowing full moon is visible. Bamboo plants and silk lanterns decorate the scene.
Important: Keep the girl’s face exactly as provided, natural and unedited, with face consistency.
Captured with the latest Canon EOS R5 and RF 50mm f/1.2L lens, ultra-high resolution, soft and diffused studio lighting to mimic moonlight, gentle cool tones with warm highlights, realistic color grading.`
  },
  {
    id: 'prompt-3',
    label: 'Bé trai & Trống',
    value: `A high-resolution studio photograph of a happy young Vietnamese boy wearing a traditional blue silk outfit. He is sitting on a woven mat, enthusiastically playing a small traditional drum ('trống') with wooden drumsticks. Around him are various Mid-Autumn festival items like a basket of pomelos, mooncakes, and several lit carp-shaped lanterns on the floor. The background is a simple, warm-toned wall suggesting a cozy home setting.
Important: Keep the boy’s face exactly as provided, natural and unedited, with face consistency.
Captured with the latest Sony A7R IV and a G Master 50mm f/1.2 lens, ultra-high resolution, warm and inviting studio lighting, rich and vibrant color grading, creating a lively and authentic atmosphere.`
  },
  {
    id: 'prompt-4',
    label: 'Bé gái & Đèn lồng cá chép',
    value: `A high-resolution studio photograph of a sweet young Vietnamese girl in a yellow traditional dress ('yếm' and skirt), sitting on a small bamboo boat decoration. She is holding a large, glowing carp-shaped lantern with both hands, looking at it with a sense of wonder. The floor is decorated with faux water lilies and floating candles. The background is a deep blue, representing a night sky with a large, bright full moon.
Important: Keep the girl’s face exactly as provided, natural and unedited, with face consistency.
Captured with the latest Canon EOS R5 and RF 85mm f/1.2L lens, ultra-high resolution, dramatic studio lighting with a strong key light, deep and contrasting colors, creating a magical and dreamlike scene.`
  },
  {
    id: 'prompt-13',
    label: 'Bé gái 1',
    value: `A high-resolution studio photography of a young girl in a Mid-Autumn Festival setup. She is wearing a luxurious red silk halter top with dragonfly embroidery, styled with black skirt, sitting on a patterned carpet. She is smiling brightly and holding two traditional mooncakes in her hands. Her hairstyle is neat with two buns tied with red ribbons. The background includes a large glowing full moon, red curtains, red lanterns, colorful fish-shaped lanterns, a lion dance head, and traditional star-shaped lanterns. A small wooden tea table with teapot and decorations is beside her. 
Important: Keep the girl’s face exactly as provided, natural and unedited, with face consistency.  
Captured with the latest Canon EOS R5 and RF 85mm f/1.2L lens, ultra-high resolution, natural studio lighting with soft diffusion, gentle warm tones, realistic color grading, balanced highlights and shadows, creating a natural, authentic studio photography look.`
  },
  {
    id: 'prompt-14',
    label: 'Bé gái 2',
    value: `A high-resolution studio photography of a young girl in a Mid-Autumn Festival setup. She is wearing a traditional red velvet áo dài with an embroidered round detail on the chest, paired with white silk pants and elegant bow shoes. She is seated gracefully on a wooden bench, holding a delicate white hand fan. Her hairstyle is styled in soft curls with a decorative hairpin. The background is a serene garden at night with a large, bright full moon, glowing lanterns hanging from tree branches, and a table with mooncakes and a teapot.
Important: Keep the girl’s face exactly as provided, natural and unedited, with face consistency.
Captured with the latest Canon EOS R5 and RF 85mm f/1.2L lens, ultra-high resolution, natural studio lighting with soft diffusion, gentle warm tones, realistic color grading, balanced highlights and shadows, creating a natural, authentic studio photography look.`
  },
];

export const ADULT_PROMPT_OPTIONS: Option[] = [
  {
    id: 'adult-prompt-1',
    label: 'Áo Yếm & Thỏ Ngọc 1',
    value: `A high-resolution luxury fashion editorial portrait of a graceful young woman wearing a modernized high-fashion version of the traditional Vietnamese áo yếm. The gown is crafted from premium pastel silk in shades of soft pink, jade green, or ivory, layered with flowing chiffon and adorned with couture-level detailing. The outfit is designed with 3D lotus appliqués made from crystal and pearl, along with hand-embroidered silver threads, giving it a refined haute couture finish. The gown must remain identical and consistent across all generated images. Her accessories are minimal yet striking: a jade bracelet on her wrist and couture pearl earrings. She gently holds a small fluffy white rabbit in her arms, symbolizing the Mid-Autumn Festival. Her hair is styled in a sleek, modernized traditional updo, giving her a polished editorial look. Scene: A surreal lotus pond backdrop under a glowing full moon, styled for a luxury editorial shoot. Oversized lotus blossoms appear sculpted from glass and crystal, glowing subtly with studio lighting. The full moon acts as a spotlight, with its reflection shimmering across the water. A light layer of mist drifts across the scene for cinematic atmosphere without excessive fantasy. Her face must remain exactly the same as the provided reference face — natural, realistic, and lifelike. Do not change, morph, or stylize her facial features. The generated face must replicate the reference face with precise fidelity, preserving all unique facial lines, contours, proportions, and natural expression. Ensure the same reference face is used consistently across all outputs, with no variation. Captured with a Canon EOS R5 and RF 85mm f/1.2L lens, ultra-high resolution. Shots alternate between close-up portraits (focusing on her natural face, rabbit, and couture lotus detailing) and full-body editorial poses (standing with flowing silk in motion, sitting elegantly by the lotus pond, or posing as though on a runway). Lighting combines soft moonlight with subtle studio highlights, enhancing the silk textures, her flawless skin, and the luminous lotus details. Colors are pastel yet polished — pearl white, jade green, blush pink, and shimmering silver — creating a luxurious, dreamy, and globally appealing fashion editorial aesthetic.`
  },
  {
    id: 'adult-prompt-2',
    label: 'Áo Yếm & Thỏ Ngọc 2',
    value: `A high-resolution luxury fashion editorial portrait of a graceful young woman wearing a modernized high-fashion version of the traditional Vietnamese áo yếm. The gown is crafted from premium pastel silk in shades of soft pink, jade green, or ivory, layered with flowing chiffon and adorned with couture-level detailing. The outfit is designed with 3D lotus appliqués made from crystal and pearl, along with hand-embroidered silver threads, giving it a refined haute couture finish. The gown is consistent across all generated images, combining sensuality, elegance, and international runway appeal. Her accessories are minimal yet striking: a jade bracelet on her wrist and couture pearl earrings. She holds a small fluffy white rabbit in her arms, symbolizing the Mid-Autumn Festival, adding a tender contrast to the high-fashion styling. Her hair is styled in a sleek, modernized traditional updo, ensuring a polished editorial look. Scene: The backdrop recreates a surreal giant lotus pond under a glowing full moon, but with a luxury editorial twist. Oversized lotus blossoms appear as if sculpted from glass and crystal, glowing subtly with studio lighting. The moon shines like a spotlight in the background, its reflection shimmering across the water. Mist drifts gracefully across the scene, balanced to look cinematic and not overly fantastical. Her face must remain exactly the same as the provided reference face — natural, realistic, lifelike, and consistent across all images. Do not alter, morph, or change her facial features in any way. Ensure her facial expression and appearance remain identical across all generated images. Captured with a Canon EOS R5 and RF 85mm f/1.2L lens, ultra-high resolution. Shots alternate between close-up portraits (focusing on her refined expression, rabbit, and couture lotus details) and full-body editorial poses (standing with flowing silk in motion, sitting elegantly by the lotus pond, or posing as though on a high-fashion runway). Lighting is a mix of soft moonlight effect and high-fashion studio spotlights, creating depth, drama, and cinematic elegance. Colors are pastel yet polished — pearl white, jade green, blush pink, and shimmering silver tones — creating a luxurious, dreamy, and internationally appealing editorial aesthetic.`
  },
  {
    id: 'adult-prompt-3',
    label: 'Áo Yếm & Thỏ Ngọc 3',
    value: `A high-resolution fantasy studio portrait of a graceful young woman wearing a flowing pastel silk gown inspired by the traditional Vietnamese áo yếm. The gown is crafted from premium pastel silk in shades of soft pink, jade green, or ivory, layered with airy chiffon that floats naturally, adding elegance and movement. The outfit is consistently the same across all generated images, delicately adorned with 3D lotus flower appliqués and sparkling crystal drops resembling morning dew, creating a refined and ethereal effect. Her accessories include a jade bracelet on her wrist, kept minimal for elegance. In her arms, she gently cradles a fluffy white rabbit, adding warmth, tenderness, and symbolic connection to the Mid-Autumn Festival. Her hair is styled simply and gracefully to emphasize authenticity and refined beauty. Scene: Although captured in a studio, the backdrop is designed as a surreal giant lotus pond under the full moon. Enormous lotus blossoms float on the water and some hover gracefully mid-air, glowing softly with a subtle, dreamlike illumination. The full moon shines brightly in the sky, its reflection sparkling across the pond’s surface like liquid silver. Gentle mist drifts above the water, adding depth and atmosphere without overpowering realism. Her face must remain exactly the same as the provided reference face — natural, realistic, lifelike, and consistent across all images. Do not alter, morph, or change her facial features in any way. Ensure her facial expression and appearance stay identical and authentic in every output. Captured with a Canon EOS R5 and RF 85mm f/1.2L lens, ultra-high resolution. The shots alternate randomly between close-up portraits (focusing on her serene expression, the rabbit, and lotus detailing) and full-body portraits (showing her graceful posture, flowing silk gown, and the luminous lotus pond backdrop). Lighting simulates a soft blend of silver moonlight and gentle studio highlights, enhancing her flawless skin, the pastel silk textures, and the luminous lotus flowers. Colors are elegant and balanced, with pastel pinks, jade greens, ivory whites, and silvery moonlight tones, creating a dreamy, cinematic, and authentically Asian fantasy aesthetic.`
  },
  {
    id: 'adult-prompt-4',
    label: 'Áo Yếm & Sen Trắng',
    value: `A high-resolution fantasy portrait of a graceful young woman wearing a modernized traditional Vietnamese áo yếm inspired by royal fashion. The yếm is crafted from premium pearl-white silk chiffon, soft and flowing, with a delicate semi-sheer quality that drapes naturally. The fabric looks sensual yet refined, moving gently like water with every pose. It is embellished with subtle silver floral embroidery and fine pearl beading, shimmering softly under the moonlight. The halter-style yếm reveals her elegant shoulders and ties at the back with long, flowing satin ribbons. Around her waist, airy layers of silk chiffon cascade like lotus petals, creating a dreamy, ethereal, and luxurious silhouette. The material is soft, delicate, and seductive while still conveying high-class sophistication. Her accessories include a lotus-petal silk headpiece and pearl earrings, adding a refined and feminine charm. Scene: She stands gracefully on the edge of a lotus pond under the Mid-Autumn Festival moon. The lotus pond serves as a background with white lotus flowers blooming on the water, large green leaves, and smooth stones reflecting moonlight. Gentle mist drifts above the pond, while a bright full moon glows in the background, casting soft silver light that enhances her allure and the romantic atmosphere. She remains on solid ground, not in the water, so the pond is purely a scenic backdrop. Her face must remain exactly the same as the provided reference face — natural, realistic, lifelike, and consistent across all images. Do not alter, morph, or change her facial features in any way. Keep her expression and details authentic and true to the original. Her outfit and overall appearance must remain identical and consistent in all generated images. Captured with a Canon EOS R5 and RF 85mm f/1.2L lens, ultra-high resolution. Lighting blends soft silver moonlight with warm highlights, illuminating the pearl-like glow of her áo yếm and the mystical lotus pond backdrop. Colors are gentle, harmonious, and slightly diffused, creating an elegant, dreamy, and authentically poetic Vietnamese aesthetic.`
  },
  {
    id: 'adult-prompt-5',
    label: 'Áo Dài Phú Bà',
    value: `A high-resolution studio-quality portrait of an elegant young woman wearing a luxurious Vietnamese áo dài valued at 300 million VND. The gown is crafted from rare, premium silk blended with fine satin and a subtle layer of shimmering organza, giving it a luminous pearl-white glow. The fabric is extremely refined, with a soft yet structured drape that reflects light like liquid gold, making it appear undeniably expensive and exclusive. The design is minimalist yet opulent: a high collar, long fitted sleeves, and floor-length panels that flow with subtle grandeur. The simplicity of the cut enhances the richness of the fabric, ensuring that the luxury of the material itself speaks of wealth and prestige. Around the neckline and cuffs, there is delicate hand-finished detailing in platinum thread, almost invisible yet adding a couture touch that signifies exclusivity. She holds a handcrafted folding fan made of ivory-toned silk with a gold-plated handle, symbolizing refinement and status. Her hair is styled elegantly with a pearl-encrusted hairpin, completing the look of wealth and sophistication. The setting is an outdoor Mid-Autumn Festival lantern market. Rows of red, gold, and amber lanterns glow brightly, their warm light reflecting off the pearl-white áo dài, making it shimmer luxuriously under every angle. The festive backdrop contrasts with her presence, making her appear regal and elevated, as though she embodies nobility within a traditional celebration. Her face must remain exactly the same as the provided reference face, natural, realistic, and consistent across all generated images. Do not alter, morph, or change her face — it should perfectly match the original reference. Captured with a Canon EOS R5 and RF 85mm f/1.2L lens, ultra-high resolution. The camera angle is a medium full-body portrait at eye level, highlighting the richness of the pearl-white áo dài. Lighting combines soft daylight with warm golden glow from lanterns, enhancing her flawless skin, the liquid sheen of the silk, and the expensive aura of the gown. Colors are balanced between pearl white, gold, and festive red, creating a luxury, regal, and fashion-editorial aesthetic.`
  },
  {
    id: 'adult-prompt-6',
    label: 'Nữ Thần Hằng Nga',
    value: `A high-resolution fantasy portrait of a celestial goddess inspired by Chang’e, the Moon Lady. She wears a flowing gown made of fine silk in pure white or soft pastel pink, with long sleeves draped in delicate chiffon layers. The dress is adorned with subtle pearl accents and embroidered laurel moon motifs, adding refinement and divine elegance. Her accessories include a traditional round silk fan in one hand, a jade hairpin delicately placed in her styled hair, and a small white jade rabbit resting gently in her arms. Her appearance radiates grace and purity, like a goddess descending from the moon. The background depicts a mystical lunar palace scene with a giant glowing full moon behind her, surrounded by drifting clouds and soft mist. The atmosphere is filled with ethereal beauty: layers of floating clouds illuminated by cool, soft moonlight in shades of pale blue and white. ⚠️ Her face must remain exactly the same as the provided reference face, kept natural, realistic, and consistent across all generated images. Do not alter or morph the face — it should perfectly match the original reference. Captured with a Canon EOS R5 and RF 85mm f/1.2L lens, ultra-high resolution, cinematic depth of field. The camera angle is a medium full-body portrait at eye level, highlighting her flowing gown and divine pose. Lighting is soft, diffused, with a cool-toned glow that enhances her flawless skin, the shimmering chiffon layers, and the celestial moonlight. Colors are elegant and balanced, dominated by white, soft pink, and moonlit blue, creating a serene, ethereal, and otherworldly aesthetic.`
  },
  {
    id: 'adult-prompt-7',
    label: 'Yếm Lụa & Lồng Đèn',
    value: `A high-resolution artistic portrait of an elegant woman wearing a luxurious, traditional-inspired outfit. The top is a sleeveless halter blouse made of fine silk, decorated with a vivid lotus and water lily print in shades of turquoise, emerald green, and orange. The design is elegant, flowing, and culturally inspired, with intricate floral motifs symbolizing grace and tradition. The skirt is multi-layered and voluminous, made of high-quality tulle fabric in rich, vibrant colors: deep red at the bottom, dark emerald green in the middle, and golden yellow near the top. The layers are soft, airy, and flowing, creating a dramatic and regal silhouette. Her accessories include jade-green statement earrings and a delicate silver hair ornament placed elegantly in her tied-up hairstyle. She gracefully holds a traditional red lantern, adding a festive and cultural highlight to the scene. The background features an artistic painted wall with natural textures, resembling a traditional East Asian mural with tones of muted green, beige, and hints of floral blossoms, providing depth and elegance. ⚠️ Her face must remain exactly the same as the provided reference face, kept natural, realistic, and consistent across all generated images. Do not alter or morph the face — it should perfectly match the original reference. Captured with a Canon EOS R5 and RF 85mm f/1.2L lens, ultra-high resolution. The camera angle is a medium full-body portrait at eye level, focusing on her graceful pose while holding the lantern. Lighting is soft and diffused, studio-style, enhancing her flawless skin, the sheen of the silk blouse, the airy textures of the tulle skirt, and the vibrant lantern colors. The overall mood is elegant, festive, and artistically traditional.`
  },
  {
    id: 'adult-prompt-8',
    label: 'Đầm Trắng & Thỏ Ngọc',
    value: `A high-resolution studio portrait of a graceful woman dressed in a flowing white silk halter dress with soft chiffon layers. The gown is designed with delicate fabric that drapes naturally, creating an ethereal and luxurious look. She wears her long dark hair half-up, decorated with a simple white accessory, enhancing her elegance and purity. She sits gracefully on a draped stage, holding a small fluffy white rabbit in her hands, looking at it tenderly. The background features sheer white curtains and a large glowing full moon, symbolizing a dreamy Mid-Autumn Festival atmosphere. Mist and soft fog effects are added at the bottom of the frame, giving the image a magical, celestial feeling. ⚠️ Her face must remain exactly the same as the provided reference face, kept natural, realistic, and consistent across all generated images. Do not alter, morph, or change her face — it should perfectly match the original reference. Captured with a Canon EOS R5 and RF 85mm f/1.2L lens, ultra-high resolution, cinematic depth of field. Lighting is soft, diffused studio light with cool highlights, enhancing her flawless skin, the flowing silk fabric, and the glowing moonlight. Colors are elegant, balanced, and ethereal, creating a dreamy and luxury studio aesthetic.`
  },
  {
    id: 'adult-prompt-9',
    label: 'Áo Dài & Quạt Tay',
    value: `A high-resolution studio portrait of an elegant woman in a luxurious traditional pink áo dài-inspired gown. The outfit is crafted from premium silk brocade fabric with subtle floral patterns, creating a refined and expensive look. The fabric drapes smoothly with a soft sheen, emphasizing its high-end, delicate quality. She sits gracefully on a wooden chair, holding an ornate hand fan decorated with floral details, exuding charm and sophistication. Her hairstyle is sleek with a hairpin accessory, completing the elegant aesthetic. She is placed in an elegant indoor setting with a soft pink fabric backdrop, cherry blossom branches in a tall ceramic vase, and a decorative white paper umbrella with floral motifs on the floor. The scene blends traditional beauty with luxury refinement. ⚠️ Her face must remain exactly the same as the provided reference face, kept natural, realistic, and consistent across all generated images. Do not alter, morph, or change her face — it should perfectly match the original reference. Captured with a Canon EOS R5 and RF 85mm f/1.2L lens, ultra-high resolution, cinematic depth of field. The camera angle is a medium full-body portrait at eye level, highlighting her elegant pose, facial expression, and the premium details of her outfit. Lighting is soft, diffused studio light with gentle highlights, enhancing her flawless skin, the silky textures of the áo dài, and the pastel pink tones of the background. Colors are elegant, balanced, and refined, with a luxury studio aesthetic.`
  },
  {
    id: 'adult-prompt-10',
    label: 'Yếm Đỏ & Lồng Đèn',
    value: `A high-resolution studio portrait of an elegant young woman in a traditional Asian-inspired outfit. She wears a red flowing silk skirt paired with a white corset-style top decorated with intricate red floral patterns. Her long black hair is styled in a sleek braid adorned with a bright red floral accessory. She gracefully holds an open red fan near her face, striking a poised and feminine pose. ⚠️ Her face must remain exactly the same as the given reference face, perfectly preserved without any alteration, and consistent across all generated images. The background features festive red lanterns and decorative branches with red blossoms, creating a vibrant Lunar New Year atmosphere. The camera angle is a three-quarter view at eye level, capturing her upper body in sharp detail. Captured with a Canon EOS R5 and RF 85mm f/1.2L lens, ultra-high resolution. Lighting is soft studio light with warm highlights, enhancing the silk textures, her flawless skin, and the vivid red tones of the outfit and decorations. Colors are rich, elegant, and balanced, emphasizing the festive red theme while keeping a luxurious aesthetic.`
  },
];


// FIX: Add ASPECT_RATIO_OPTIONS to fix import error in App.tsx
export const ASPECT_RATIO_OPTIONS: Option[] = [
  { id: 'ar-1', label: '1:1 Vuông', value: '1:1' },
  { id: 'ar-2', label: '3:4 Đứng', value: '3:4' },
  { id: 'ar-3', label: '9:16 Story', value: '9:16' },
];

// FIX: Add QUALITY_OPTIONS to fix import error in App.tsx
export const QUALITY_OPTIONS: Option[] = [
  { id: 'q-1', label: 'Tiêu chuẩn', value: 'Standard Definition' },
  { id: 'q-2', label: 'Cao', value: 'High Definition' },
  { id: 'q-3', label: 'Rất cao', value: 'Ultra High Definition' },
];